# Powerlevel10k configuration for the cyberpunk WezTerm theme.
# Installed to ~/.p10k.zsh by install.sh.

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
typeset -g POWERLEVEL9K_MODE=nerdfont-complete
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon
  dir
  vcs
  newline
  prompt_char
)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  background_jobs
  direnv
  asdf
  virtualenv
  node_version
  python_version
  go_version
  rust_version
  dotnet_version
  php_version
  java_version
  docker_context
  time
)

function prompt_python_version() {
  local python=${commands[python]:-${commands[python3]}}
  [[ -n $python ]] || return

  local version
  version=$($python --version 2>/dev/null) || return
  [[ $version == Python\ * ]] || return

  p10k segment -f 117 -i 'PYTHON' -t "${version#Python }"
}

typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=255
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=
typeset -g POWERLEVEL9K_DIR_FOREGROUND=111
typeset -g POWERLEVEL9K_DIR_BACKGROUND=
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=250
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=153
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=114
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=179
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=174
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR=114
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=114
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=204
typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
typeset -g POWERLEVEL9K_STATUS_OK=true
typeset -g POWERLEVEL9K_STATUS_ERROR=true
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=114
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=
typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✓'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=218
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=
typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✕'
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=218
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=221
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=232
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=
typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=232
typeset -g POWERLEVEL9K_DIRENV_BACKGROUND=
typeset -g POWERLEVEL9K_ASDF_FOREGROUND=232
typeset -g POWERLEVEL9K_ASDF_BACKGROUND=
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=232
typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=
typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=114
typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND=
typeset -g POWERLEVEL9K_NODE_VERSION_VISUAL_IDENTIFIER_EXPANSION='NodeJS'
typeset -g POWERLEVEL9K_PYTHON_VERSION_FOREGROUND=117
typeset -g POWERLEVEL9K_PYTHON_VERSION_BACKGROUND=
typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND=159
typeset -g POWERLEVEL9K_GO_VERSION_BACKGROUND=
typeset -g POWERLEVEL9K_GO_VERSION_VISUAL_IDENTIFIER_EXPANSION='Go'
typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=223
typeset -g POWERLEVEL9K_RUST_VERSION_BACKGROUND=
typeset -g POWERLEVEL9K_RUST_VERSION_VISUAL_IDENTIFIER_EXPANSION='Rs'
typeset -g POWERLEVEL9K_DOTNET_VERSION_FOREGROUND=141
typeset -g POWERLEVEL9K_DOTNET_VERSION_BACKGROUND=
typeset -g POWERLEVEL9K_DOTNET_VERSION_PROJECT_ONLY=true
typeset -g POWERLEVEL9K_DOTNET_VERSION_VISUAL_IDENTIFIER_EXPANSION='.NET'
typeset -g POWERLEVEL9K_PHP_VERSION_FOREGROUND=183
typeset -g POWERLEVEL9K_PHP_VERSION_BACKGROUND=
typeset -g POWERLEVEL9K_PHP_VERSION_PROJECT_ONLY=true
typeset -g POWERLEVEL9K_PHP_VERSION_VISUAL_IDENTIFIER_EXPANSION='PHP'
typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND=117
typeset -g POWERLEVEL9K_JAVA_VERSION_BACKGROUND=
typeset -g POWERLEVEL9K_JAVA_VERSION_PROJECT_ONLY=true
typeset -g POWERLEVEL9K_JAVA_VERSION_FULL=false
typeset -g POWERLEVEL9K_JAVA_VERSION_VISUAL_IDENTIFIER_EXPANSION='Java'
typeset -g POWERLEVEL9K_DOCKER_CONTEXT_FOREGROUND=232
typeset -g POWERLEVEL9K_DOCKER_CONTEXT_BACKGROUND=
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=222
typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
typeset -g POWERLEVEL9K_TIME_FOREGROUND=183
typeset -g POWERLEVEL9K_TIME_BACKGROUND=
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true
